## **Fit a basic model**

**This happens only on the training set**

In [25]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

tr_features = pd.read_csv('train_features.csv')
tr_labels = pd.read_csv('train_labels.csv', header=None)

In [26]:
tr_labels.head(10)

        0    1                  2        3           4          5
0  Pclass  Sex                Age     Fare  Family_cnt  Cabin_ind
1       2    0               62.0     10.5           0          0
2       3    0                8.0   29.125           5          0
3       3    0               32.0  56.4958           0          0
4       3    1               20.0    9.825           1          0
5       2    1               28.0     13.0           0          0
6       3    1               21.0     7.75           0          0
7       3    0               37.0    7.925           2          0
8       3    1               17.0  14.4583           0          0
9       3    1  29.69911764705882     7.75           0          0

In [27]:
tr_features.head(10)

   Pclass  Sex        Age     Fare  Family_cnt  Cabin_ind
0       2    0  62.000000  10.5000           0          0
1       3    0   8.000000  29.1250           5          0
2       3    0  32.000000  56.4958           0          0
3       3    1  20.000000   9.8250           1          0
4       2    1  28.000000  13.0000           0          0
5       3    1  21.000000   7.7500           0          0
6       3    0  37.000000   7.9250           2          0
7       3    1  17.000000  14.4583           0          0
8       3    1  29.699118   7.7500           0          0
9       1    0  46.000000  61.1750           1          1

In [28]:
rf = RandomForestClassifier()
scores = cross_val_score(rf, tr_features, tr_labels.values.ravel(), cv=5)

ValueError: Found input variables with inconsistent numbers of samples: [534, 3210]